### ISSUE TITLE
Investigate how to use an EBS disk and if we need it

### ISSUE THREAD

**Issue by DavideD** [hibernate/ci.hibernate.org#4]
At the moment we have started an image that create an EBS disk where we save the jenkins workspace (this part is not scripted).

The EBS disk is created new everytime a machine is started but what we need is to use an image that doesn't create an EBS disk and attach one that already exists.
Maybe we don't need an EBS disk at all if we use a different image.
We need to investagat possible solution and update the script to apply them

**Comment by Sanne** [comment]
outdated: moved to use Ansible now, and tracking issues on JIRA.
